"""005_annotation_label_text

Revision ID: 80f7e31435e9
Revises: 004_real_dataset_import
Create Date: 2026-09-06 07:55:27.115042
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '80f7e31435e9'
down_revision: Union[str, None] = '004_real_dataset_import'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'label',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
