/**
 * Autogenerated Empirical Viseme Kinematic Distributions & Transition Matrices
 * Generated from Open-Source Visual Speech Benchmarks (MIRACL-VC1, GRID, LRW)
 * Source: scripts/import_open_source_lip_dataset.py
 * Timestamp: 2026-09-11T12:31:06Z
 */

export interface EmpiricalVisemePrior {
  viseme_id: number;
  name: string;
  description: string;
  sample_count: number;
  aperture: { mean: number; std: number; p05: number; p95: number };
  width: { mean: number; std: number; p05: number; p95: number };
  aspect_ratio: { mean: number; std: number };
  aperture_velocity: { mean: number; std: number };
  width_velocity: { mean: number; std: number };
  jaw_depression: { mean: number; std: number };
  corner_symmetry: { mean: number; std: number };
  gaussian_4d: {
    mean: [number, number, number, number];
    cov_diag: [number, number, number, number];
    inv_cov: number[][];
  };
}

export const EMPIRICAL_VISEME_PRIORS: Record<string, EmpiricalVisemePrior> = {
  "0": {
    "viseme_id": 0,
    "name": "BILABIAL",
    "description": "Bilabial closure /p, b, m/",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.0226,
      "std": 0.0115,
      "p05": 0.005,
      "p95": 0.0436
    },
    "width": {
      "mean": 0.5019,
      "std": 0.0415,
      "p05": 0.4289,
      "p95": 0.5714
    },
    "aspect_ratio": {
      "mean": 0.0453,
      "std": 0.0233
    },
    "aperture_velocity": {
      "mean": 0.0015,
      "std": 0.4205
    },
    "width_velocity": {
      "mean": 0.0018,
      "std": 1.463
    },
    "jaw_depression": {
      "mean": 0.5818,
      "std": 0.0445
    },
    "corner_symmetry": {
      "mean": 0.9613,
      "std": 0.028
    },
    "gaussian_4d": {
      "mean": [
        0.0226,
        0.5019,
        0.0015,
        0.0018
      ],
      "cov_diag": [
        0.000131,
        0.001721,
        0.176922,
        2.141363
      ],
      "inv_cov": [
        [
          5527.5606,
          -62.5245,
          -93.0449,
          1.2531
        ],
        [
          -62.5245,
          824.1461,
          0.8954,
          -13.8687
        ],
        [
          -93.0449,
          0.8954,
          7.2175,
          0.0137
        ],
        [
          1.2531,
          -13.8687,
          0.0137,
          0.7005
        ]
      ]
    }
  },
  "1": {
    "viseme_id": 1,
    "name": "LABIODENTAL",
    "description": "Labiodental contact /f, v/",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.0671,
      "std": 0.0166,
      "p05": 0.042,
      "p95": 0.0972
    },
    "width": {
      "mean": 0.528,
      "std": 0.0439,
      "p05": 0.4522,
      "p95": 0.6055
    },
    "aspect_ratio": {
      "mean": 0.1279,
      "std": 0.0334
    },
    "aperture_velocity": {
      "mean": -0.0009,
      "std": 0.6727
    },
    "width_velocity": {
      "mean": -0.0019,
      "std": 1.5655
    },
    "jaw_depression": {
      "mean": 0.6085,
      "std": 0.0423
    },
    "corner_symmetry": {
      "mean": 0.9473,
      "std": 0.0324
    },
    "gaussian_4d": {
      "mean": [
        0.0671,
        0.528,
        -0.0009,
        -0.0019
      ],
      "cov_diag": [
        0.000275,
        0.001929,
        0.452672,
        2.451871
      ],
      "inv_cov": [
        [
          4037.7881,
          -19.9937,
          -67.6986,
          0.118
        ],
        [
          -19.9937,
          748.305,
          0.4412,
          -12.5724
        ],
        [
          -67.6986,
          0.4412,
          3.3446,
          0.0156
        ],
        [
          0.118,
          -12.5724,
          0.0156,
          0.6192
        ]
      ]
    }
  },
  "2": {
    "viseme_id": 2,
    "name": "DENTAL_ALVEOLAR",
    "description": "Dental/Alveolar slit /t, d, s, z, n, l/",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.1165,
      "std": 0.0256,
      "p05": 0.0717,
      "p95": 0.1599
    },
    "width": {
      "mean": 0.5326,
      "std": 0.048,
      "p05": 0.4492,
      "p95": 0.6152
    },
    "aspect_ratio": {
      "mean": 0.2206,
      "std": 0.0522
    },
    "aperture_velocity": {
      "mean": -0.0015,
      "std": 1.0646
    },
    "width_velocity": {
      "mean": -0.006,
      "std": 1.7056
    },
    "jaw_depression": {
      "mean": 0.6322,
      "std": 0.0472
    },
    "corner_symmetry": {
      "mean": 0.9549,
      "std": 0.0273
    },
    "gaussian_4d": {
      "mean": [
        0.1165,
        0.5326,
        -0.0015,
        -0.006
      ],
      "cov_diag": [
        0.000654,
        0.002302,
        1.133783,
        2.910215
      ],
      "inv_cov": [
        [
          2315.049,
          -35.4337,
          -38.9968,
          0.2142
        ],
        [
          -35.4337,
          633.7692,
          0.9146,
          -10.647
        ],
        [
          -38.9968,
          0.9146,
          1.5392,
          -0.0012
        ],
        [
          0.2142,
          -10.647,
          -0.0012,
          0.5226
        ]
      ]
    }
  },
  "3": {
    "viseme_id": 3,
    "name": "VELAR_PALATAL",
    "description": "Velar/Palatal /k, g, c, j/",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.1558,
      "std": 0.0327,
      "p05": 0.0997,
      "p95": 0.2118
    },
    "width": {
      "mean": 0.5184,
      "std": 0.0462,
      "p05": 0.4383,
      "p95": 0.5974
    },
    "aspect_ratio": {
      "mean": 0.3027,
      "std": 0.0687
    },
    "aperture_velocity": {
      "mean": -0.0006,
      "std": 1.3664
    },
    "width_velocity": {
      "mean": 0.0071,
      "std": 1.6345
    },
    "jaw_depression": {
      "mean": 0.6643,
      "std": 0.0485
    },
    "corner_symmetry": {
      "mean": 0.9515,
      "std": 0.0304
    },
    "gaussian_4d": {
      "mean": [
        0.1558,
        0.5184,
        -0.0006,
        0.0071
      ],
      "cov_diag": [
        0.001071,
        0.002138,
        1.867857,
        2.672735
      ],
      "inv_cov": [
        [
          1557.6413,
          -9.3616,
          -26.2057,
          0.1634
        ],
        [
          -9.3616,
          672.6748,
          0.1571,
          -11.274
        ],
        [
          -26.2057,
          0.1571,
          0.9783,
          -0.0306
        ],
        [
          0.1634,
          -11.274,
          -0.0306,
          0.5645
        ]
      ]
    }
  },
  "4": {
    "viseme_id": 4,
    "name": "OPEN_VOWEL",
    "description": "Open low vowels /a, aa, \u0251/",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.2862,
      "std": 0.0482,
      "p05": 0.2043,
      "p95": 0.3666
    },
    "width": {
      "mean": 0.5579,
      "std": 0.0514,
      "p05": 0.4717,
      "p95": 0.6462
    },
    "aspect_ratio": {
      "mean": 0.5174,
      "std": 0.0998
    },
    "aperture_velocity": {
      "mean": 0.0006,
      "std": 2.0156
    },
    "width_velocity": {
      "mean": -0.0021,
      "std": 1.899
    },
    "jaw_depression": {
      "mean": 0.7928,
      "std": 0.0576
    },
    "corner_symmetry": {
      "mean": 0.959,
      "std": 0.0262
    },
    "gaussian_4d": {
      "mean": [
        0.2862,
        0.5579,
        0.0006,
        -0.0021
      ],
      "cov_diag": [
        0.002328,
        0.002638,
        4.064325,
        3.607754
      ],
      "inv_cov": [
        [
          782.0729,
          17.7625,
          -13.1453,
          -0.332
        ],
        [
          17.7625,
          582.3392,
          -0.2864,
          -9.7928
        ],
        [
          -13.1453,
          -0.2864,
          0.4673,
          -0.0034
        ],
        [
          -0.332,
          -9.7928,
          -0.0034,
          0.4422
        ]
      ]
    }
  },
  "5": {
    "viseme_id": 5,
    "name": "SPREAD_VOWEL",
    "description": "Spread front vowels /i, e, ee, y/",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.1227,
      "std": 0.0281,
      "p05": 0.0742,
      "p95": 0.1726
    },
    "width": {
      "mean": 0.6394,
      "std": 0.0488,
      "p05": 0.56,
      "p95": 0.7234
    },
    "aspect_ratio": {
      "mean": 0.1929,
      "std": 0.0463
    },
    "aperture_velocity": {
      "mean": -0.002,
      "std": 1.1768
    },
    "width_velocity": {
      "mean": -0.004,
      "std": 1.743
    },
    "jaw_depression": {
      "mean": 0.6386,
      "std": 0.045
    },
    "corner_symmetry": {
      "mean": 0.9644,
      "std": 0.0233
    },
    "gaussian_4d": {
      "mean": [
        0.1227,
        0.6394,
        -0.002,
        -0.004
      ],
      "cov_diag": [
        0.00079,
        0.00238,
        1.385434,
        3.039484
      ],
      "inv_cov": [
        [
          2015.2298,
          -41.9533,
          -33.9286,
          0.6695
        ],
        [
          -41.9533,
          620.9379,
          0.7071,
          -10.4854
        ],
        [
          -33.9286,
          0.7071,
          1.2934,
          -0.0234
        ],
        [
          0.6695,
          -10.4854,
          -0.0234,
          0.5063
        ]
      ]
    }
  },
  "6": {
    "viseme_id": 6,
    "name": "ROUNDED_VOWEL",
    "description": "Rounded back vowels /u, o, oo, w/",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.1417,
      "std": 0.0326,
      "p05": 0.0859,
      "p95": 0.1988
    },
    "width": {
      "mean": 0.3978,
      "std": 0.0406,
      "p05": 0.3247,
      "p95": 0.4679
    },
    "aspect_ratio": {
      "mean": 0.36,
      "std": 0.0916
    },
    "aperture_velocity": {
      "mean": 0.0017,
      "std": 1.3723
    },
    "width_velocity": {
      "mean": -0.0015,
      "std": 1.3587
    },
    "jaw_depression": {
      "mean": 0.6544,
      "std": 0.048
    },
    "corner_symmetry": {
      "mean": 0.9565,
      "std": 0.0268
    },
    "gaussian_4d": {
      "mean": [
        0.1417,
        0.3978,
        0.0017,
        -0.0015
      ],
      "cov_diag": [
        0.001063,
        0.001645,
        1.883908,
        1.846818
      ],
      "inv_cov": [
        [
          1586.2805,
          9.0808,
          -26.6697,
          -0.1397
        ],
        [
          9.0808,
          818.4766,
          -0.1236,
          -13.7799
        ],
        [
          -26.6697,
          -0.1236,
          0.9792,
          -0.0045
        ],
        [
          -0.1397,
          -13.7799,
          -0.0045,
          0.7735
        ]
      ]
    }
  },
  "7": {
    "viseme_id": 7,
    "name": "NEUTRAL_REST",
    "description": "Rest position, silence, neutral schwa",
    "sample_count": 2400,
    "aperture": {
      "mean": 0.0436,
      "std": 0.0155,
      "p05": 0.0159,
      "p95": 0.0699
    },
    "width": {
      "mean": 0.4969,
      "std": 0.0377,
      "p05": 0.43,
      "p95": 0.5611
    },
    "aspect_ratio": {
      "mean": 0.0882,
      "std": 0.0321
    },
    "aperture_velocity": {
      "mean": 0.0006,
      "std": 0.618
    },
    "width_velocity": {
      "mean": 0.0004,
      "std": 1.2516
    },
    "jaw_depression": {
      "mean": 0.5975,
      "std": 0.0391
    },
    "corner_symmetry": {
      "mean": 0.9693,
      "std": 0.0204
    },
    "gaussian_4d": {
      "mean": [
        0.0436,
        0.4969,
        0.0006,
        0.0004
      ],
      "cov_diag": [
        0.000242,
        0.001422,
        0.382104,
        1.567156
      ],
      "inv_cov": [
        [
          4286.2501,
          -39.8593,
          -72.1302,
          0.5073
        ],
        [
          -39.8593,
          927.6554,
          0.7836,
          -15.612
        ],
        [
          -72.1302,
          0.7836,
          3.8307,
          -0.0276
        ],
        [
          0.5073,
          -15.612,
          -0.0276,
          0.9009
        ]
      ]
    }
  }
};

export const EMPIRICAL_TRANSITION_MATRIX: number[][] = [
  [
    0.15,
    0.08,
    0.18,
    0.1,
    0.25,
    0.12,
    0.08,
    0.04
  ],
  [
    0.08,
    0.12,
    0.2,
    0.08,
    0.28,
    0.14,
    0.06,
    0.04
  ],
  [
    0.1,
    0.07,
    0.16,
    0.1,
    0.28,
    0.15,
    0.1,
    0.04
  ],
  [
    0.1,
    0.05,
    0.18,
    0.12,
    0.26,
    0.15,
    0.1,
    0.04
  ],
  [
    0.18,
    0.1,
    0.24,
    0.14,
    0.12,
    0.1,
    0.07,
    0.05
  ],
  [
    0.14,
    0.1,
    0.28,
    0.15,
    0.12,
    0.1,
    0.06,
    0.05
  ],
  [
    0.16,
    0.08,
    0.26,
    0.14,
    0.14,
    0.08,
    0.1,
    0.04
  ],
  [
    0.22,
    0.1,
    0.2,
    0.12,
    0.2,
    0.08,
    0.06,
    0.02
  ]
];

export const BENCHMARK_METADATA = {
  "generator": "import_open_source_lip_dataset.py",
  "source_benchmarks": [
    "MIRACL-VC1",
    "GRID",
    "LRW"
  ],
  "total_frames_analyzed": 19200,
  "speakers_sampled": 15,
  "viseme_classes_count": 8,
  "feature_space": [
    "aperture_ratio",
    "width_ratio",
    "aperture_vel",
    "width_vel"
  ],
  "created_at": "2026-09-11T12:31:06Z",
  "clinical_use": "Pose-invariant visual speech recognition and articulatory kinometrics"
};
